

export interface Irickandmorty {
}
// Generated by https://quicktype.io

export interface Personajes {
    info:    Info;
    results: Personaje[];
}

export interface Info {
    count: number;
    pages: number;
    next:  string;
    prev:  null;
}

export interface Personaje {
    id:       number;
    name:     string;
    status:   Status;
    species:  Species;
    type:     Type;
    gender:   Gender;
    origin:   Location;
    location: Location;
    image:    string;
    episode:  string[];
    url:      string;
    created:  Date;
}

export enum Gender {
    Female = "Female",
    Male = "Male",
}

export interface Location {
    name: string;
    url:  string;
}

export enum Species {
    Alien = "Alien",
    Human = "Human",
    Unknown = "unknown",
}

export enum Status {
    Alive = "Alive",
}

export enum Type {
    Chair = "Chair",
    Clone = "Clone",
    Empty = "",
    Pickle = "Pickle",
}